name: 'Deploy action'
description: 'Deploy action'
inputs:
  target-env:
    required: true
  ssh_key:
    required: true
  ssh_host:
    required: true
  ssh_port:
    required: true
#outputs:
#  random-number:
#    description: "Random number"
#    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo "ðŸŽ‰ target evn ${{ inputs.target-env}}"
      shell: bash
    - run: echo "ðŸŽ‰ target evn inputs.target-env"
      shell: bash
    - run: echo "ðŸ is Dev  ${{ inputs.target-env }} == 'Development'"
      shell: bash
    - run: echo "ðŸ§ is Prod  ${{ inputs.target-env }} == 'Production'"
      shell: bash
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ inputs.ssh_key }}
        known_hosts: unnecessary

    - name: Adding Known Hosts
      run: ssh-keyscan -p ${{ inputs.ssh_port}} -H ${{ inputs.ssh_host }}  >> ~/.ssh/known_hosts
    #  shell: bash

    - name: Copy backend artifact to remote host
      run: scp /home/runner/work/QueryGenerator/QueryGenerator/target/QueryGenerator-1.0-SNAPSHOT.jar  ${{ inputs.ssh_user }}@${{ inputs.ssh_host }}:/home/ubuntu
    #  shell: bash
