name: Maven build and pseudo Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: environment
        required: true

jobs:
  build_jar:
    name: Build jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean install
      - name: Upload artifact for deployment job
        uses: ./.github/workflows/main.yml
        secrets: inherit
        with:
          target-env: ${{ inputs.environment }}
 
