name: Maven build and pseudo Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: environment
        required: true

jobs:
  build_jar:
    name: Build jar and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean install

      - name: Deploy
        uses: ./.github/workflows/rf.yml
        with:
          target-env: ${{ inputs.environment }}
        #secrets: inherit
